### ISSUE TITLE
`GLIBC_2.33' not found (required by ./frozenight)

### ISSUE THREAD

**Issue by tsoj** [MinusKelvin/frozenight#5]
`/frozenight: /lib64/libc.so.6: version 'GLIBC_2.33' not found (required by ./frozenight)`

Linux binary seems to be linked for shared libraries. However, that specific libraries are installed (such as GLIBC_2.33) is not always guaranteed. A fix would be to link your release binaries statically.

**Comment by MinusKelvin** [comment]
Ah right, this issue. There is no reason why Frozenight couldn't use glibc 2.17 (the minimum version supported by Rust) but for some asinine reason it's impossible to target any version of glibc earlier than the one installed on the host system.

I'll be sure to fix this in future releases.

**Comment by MinusKelvin** [comment]
Compiling Frozenight in a container using `cross` allowed compiling against glibc 2.18, so the recently released version 6.0.0 binaries should not be affected by this problem.
